# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# create app directory
WORKDIR /app

# install dependencies
COPY package.json package-lock.json tsconfig.json ./
RUN npm install --ignore-scripts

# copy source
COPY . .

# build TypeScript
RUN npm run build

# expose stdio transport (no ports)
# default command
CMD ["node", "build/payman-server.js"]
