# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Multi-stage Dockerfile for Payman MCP Server

# Build stage: install dev dependencies and compile TypeScript
FROM node:lts-alpine AS builder
WORKDIR /app

# Copy package files and tsconfig
COPY package.json package-lock.json tsconfig.json ./

# Install all dependencies (including dev) for build
RUN npm install

# Copy all source files
COPY . .

# Build TypeScript to JavaScript
RUN npm run build

# Production stage: install only production dependencies
FROM node:lts-alpine AS runtime
WORKDIR /app

# Copy package.json to install runtime deps
COPY package.json package-lock.json ./
RUN npm install --production

# Copy compiled build artifacts from builder
COPY --from=builder /app/build ./build

# Expose no ports; server uses stdio

# Default command to run the MCP server
CMD ["node", "build/payman-server.js"]
